# Análise exploratória dos dados

---
## Configuração do ambiente

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('../data/processed/cleaned_data.csv')

In [2]:
df.sample(5, random_state=42)

,curso,setor,campus,grau,turno,ano,ingressantes_ps,ingressantes_sisu,ingressantes_provar,ingressantes_outros,matriculados,evadidos,concluintes
1178,Terapia Ocupacional,Ciências da Saúde,Centro - Saúde,Bacharelado,N,2024,57,8,1,5,266,46,21
865,Pedagogia,Educação,Centro - Reitoria,Licenciatura,M,2020,59,13,0,7,347,7,50
101,Educação do Campo,Desconhecido,Litoral (Matinhos),Licenciatura,I,2018,33,0,0,0,207,17,47
439,Computação,Desconhecido,Jandaia do Sul,Licenciatura,T,2023,3,1,0,40,43,39,2
58,Letras - Italiano,Ciências Humanas,Centro - Reitoria,Múltiplo,M,2018,19,1,2,2,95,6,8

In [3]:
df.head()

,curso,setor,campus,grau,turno,ano,ingressantes_ps,ingressantes_sisu,ingressantes_provar,ingressantes_outros,matriculados,evadidos,concluintes
0,Artes Visuais,"Artes, Comunicação e Design",Juvevê (SACOD),Bacharelado,T,2018,14,2,0,4,68,6,12
1,Artes Visuais,"Artes, Comunicação e Design",Juvevê (SACOD),Licenciatura,T,2018,13,1,0,2,63,11,13
2,Jornalismo,"Artes, Comunicação e Design",Juvevê (SACOD),Bacharelado,I,2018,26,4,0,1,118,6,27
3,Publicidade e Propaganda,"Artes, Comunicação e Design",Juvevê (SACOD),Bacharelado,I,2018,24,5,0,0,120,11,20
4,Relações Públicas,"Artes, Comunicação e Design",Juvevê (SACOD),Bacharelado,I,2018,24,5,0,0,117,8,28