# Análise exploratória dos dados

---
## Configuração do ambiente

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('../data/interim/data_loaded.csv')
c_df = pd.read_csv('../data/processed/data_cleaned.csv')

In [2]:
df.sample(5, random_state=42)

,curso,setor,campus,grau,turno,ano,vagas_ps,inscritos_ps,aprovados_ps,ingressantes_ps,rel_cand_vaga,vagas_sisu,ingressantes_sisu,ingressantes_provar,ingressantes_outros,matriculados,evadidos,concluintes
890,Engenharia Elétrica,Setor de Tecnologia,Campus Centro Politécnico,Bacharelado,I,2020,80,307,104,88,"3,79",20,21,0,8,"239,50",34,62
115,Gestão de Turismo,Litoral,Campus Litoral (Matinhos),Tecnológico,N,2018,28,0,28,26,"0,00",7,2,2,0,95,26,11
543,Geografia,Setor de Ciências da Terra,Campus Centro Politécnico,Licenciatura,N,2023,32,39,30,0,1.18,8,0,0,0,75.0,27,17
175,Física,Setor de Ciências Exatas,Campus Centro Politécnico,Bacharelado,M,2019,56,183,64,55,"3,27",14,13,0,10,"227,00",47,18
63,Letras - Libras,Setor de Ciências Humanas,Campus Centro - Reitoria,Licenciatura,N,2018,0,0,17,17,"0,00",0,4,6,6,78,13,6

In [3]:
c_df.loc[c_df['grau'] == 'Desconhecido', 'ano'].value_counts()

ano
2025    186
Name: count, dtype: int64

In [6]:
len(c_df[c_df['ano'] == 2025])

186

In [4]:
c_df[(c_df['grau'] != 'Desconhecido') & (c_df['ano'] == 2025)]

Empty DataFrame
Columns: [curso, setor, campus, grau, turno, ano, ingressantes_ps, ingressantes_sisu, ingressantes_provar, ingressantes_outros, matriculados, evadidos, concluintes]
Index: []